### ISSUE TITLE
500 HTTP Error

### ISSUE THREAD

**Issue by takeru579** [JeremySkinner/git-dot-aspx#6]
I'm using this program on Windows Server 2012 R2(Japanese Edition).
Sometimes I got 'HTTP Error 500' when I pushing to Server.
This problem is not everytime. I can push the data to Server but sometimes I got 'HTTP Error 500'.
However, I don't know other error-trigger.
When I got a 'HTTP Error 500', I did 'application pool recycling' on IIS.
After then It is work.

Do you have any ideas for solve a problem?
**I'm sorry, but I'm not good at English.

This is a '500 Error page'-------->
Line 15: < ul id = "repositories" >
Line 16: <% foreach (var repository in Model.Repositories) { %>
Line 17:  < li>5
Line 18:  < a class="repository" href="javascript:void(0)" title="<%"Url.ProjectUrl(repository.Name)"%>">

ソース ファイル: d:\git_aspx\Views\DirectoryList\Index.aspx    行:  16 

ソース ファイル:  d:\git_aspx\Views\DirectoryList\Index.aspx    行:  16 

スタック トレース: 

[NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。]
   GitSharp.Core.OffsetCache`2.Gc() in C:\Projects\GitSharp\GitSharp.Core\OffsetCache.cs:489
   GitSharp.Core.OffsetCache`2.removeAll(PackFile pack) in C:\Projects\GitSharp\GitSharp.Core\OffsetCache.cs:393
   GitSharp.Core.WindowCache.Purge(PackFile pack) in C:\Projects\GitSharp\GitSharp.Core\WindowCache.cs:167
   GitSharp.Core.PackFile.Close() in C:\Projects\GitSharp\GitSharp.Core\PackFile.cs:195
   GitSharp.Core.PackFile.Dispose() in C:\Projects\GitSharp\GitSharp.Core\PackFile.cs:628
   GitSharp.Core.ObjectDirectory.closeSelf() in C:\Projects\GitSharp\GitSharp.Core\ObjectDirectory.cs:111
   GitSharp.Core.ObjectDatabase.close() in C:\Projects\GitSharp\GitSharp.Core\ObjectDatabase.cs:107
   GitSharp.Core.ObjectDatabase.Dispose() in C:\Projects\GitSharp\GitSharp.Core\ObjectDatabase.cs:99
   GitSharp.Core.Repository.Close() in C:\Projects\GitSharp\GitSharp.Core\Repository.cs:943
   GitSharp.Core.Repository.Dispose() in C:\Projects\GitSharp\GitSharp.Core\Repository.cs:1394
   GitAspx.Lib.Repository.GetLatestCommit() in c:\Projects\git-dot-aspx\GitAspx\Lib\Repository.cs:64
   GitAspx.Controllers.DirectoryListController.<Index>b__1(Repository x) in c:\Projects\git-dot-aspx\GitAspx\Controllers\DirectoryListController.cs:37
   System.Linq.WhereSelectListIterator`2.MoveNext() +243
   ASP.views_directorylist_index_aspx.__RenderMain(HtmlTextWriter __w, Control parameterContainer) in d:\git_aspx\Views\DirectoryList\Index.aspx:16
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +130
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +149
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +245
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +149
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +245
   System.Web.Mvc.ViewPage.Render(HtmlTextWriter writer) +84
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +149
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5362

<----------------------------------------

Thank you for your reading.

**Comment by JeremySkinner** [comment]
Hi, I'm afraid I can't help you- this project was an experiment I worked on 5 years ago and is no longer maintained. It was never ready for production, nor has it been kept up-to-date. It doesn't support modern versions of git. 

I'd suggest finding an alternative product.
