### ISSUE TITLE
Server-Side hooks not triggering

### ISSUE THREAD

**Issue by ScriptPup** [JeremySkinner/git-dot-aspx#8]
Git hooks don't appear to be firing when using git-dot-aspx path. 

My test hook is named "post-receive" containing this:
  ```
    #!/bin/sh
      echo "post-receive hook" >> A:\Test.txt
      echo "Hooked"
```

I haven't found any way to debug or figure out what's going on, so I'm not sure what additional information I can provide.

**Comment by JeremySkinner** [comment]
Hi, I’m afraid this is an obsolete experimental project that hasn’t been under development for many years. It is no longer supported or maintained and no further updates or fixes will be made, but you are more than welcome to use the source code.
